version: "3.8"

volumes:
  certs:
    driver: local
  esdata:
    driver: local
  kibanadata:
    driver: local
  metricbeatdata01:
    driver: local
  filebeatdata01:
    driver: local
  logstashdata01:
    driver: local

networks:
  default:
    name: elastic
    external: false

services:
  es:
    image: docker.resaa.net/elasticsearch:${STACK_VERSION}
    container_name: es
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=es
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.resaa.net/kibana:9.1.5
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://192.168.21.81:9200
    ports:
      - "5601:5601"
    volumes:
      - kibanadata:/usr/share/kibana/data
    depends_on:
      - es

  nifi:
    container_name: nifi
    image: docker.resaa.net/apache/nifi:1.27.0
    environment:
      NIFI_WEB_HTTP_PORT: "8080"
    ports:
      - "8080:8080"

  airflow:
    container_name: airflow
    image: docker.resaa.net/apache/airflow:2.9.2
    command: standalone
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    ports:
      - "8081:8080"

  postgres:
    image: docker.resaa.net/postgres:16.10-alpine3.22
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data
